[tool.black]
line_length = 88
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | __pycache__
    | _build
    | build
    | dist
    | docs
    | venv
    | node_modules
    | frontend      # Exclude imported Tate repositories.
    | ui            # Exclude imported Tate repositories.
    | api           # Exclude imported Tate repositories.
    | api_client    # Exclude imported Tate repositories.
  )/
)
'''
