name: "Deploy"

on:
  release:
    types: [created]

jobs:
  publish_to_pypi:
    name: 📦 Publish to PyPi
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: ⬇️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Django>=3.2,<3.3"
          pip install "Wagtail>=2.14,<2.15"
          pip install -e .[test]
      - name: ✅ Check for missing migrations
        run: django-admin makemigrations --check --noinput
      - name: 🧪 Run tests
        run: pytest
      - name: ⬇️ Install build dependencies
        run: python -m pip install build  --user
      - name: 🏗️ Package for PyPi
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: 🚀 Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
